name: getx_prectice
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.4 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  camera: 0.11.0
  image_picker: 1.1.1
  flutter: 
    sdk: flutter
  http: ^1.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.3

dev_dependencies: 
  flutter_lints: ^3.0.0
  flutter_launcher_icons: 0.13.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

